name: tests-auth

on:
  [push, pull_request]:
    paths:
      - '23_CI_CD/app/auth/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd 23_CI_CD/app/auth && npm install && npm run test:ci
